apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: simple-argocd-project
  ports:
    - port: 80           # Port on the Service
      targetPort: 5000   # Port on the Flask container
      protocol: TCP