apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort  
  selector:
    app: simple-argocd-project
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      nodePort: 30080 # for external access without port forwarding
