apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logcollectors.mydomain.com
spec:
  group: mydomain.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                logSidecar:
                  type: object
                  properties:
                    image:
                      type: string
                    command:
                      type: array
                      items:
                        type: string
                    args:
                      type: array
                      items:
                        type: string
  scope: Namespaced
  names:
    kind: LogCollector
    plural: logcollectors
    singular: logcollector
    shortNames:
    - logc
